# Postgres Connection
spring.datasource.url=jdbc:postgresql://192.168.40.21:5432/dns_database
spring.datasource.username=bind_user
spring.datasource.password=password_dlz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Dialeto para o PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# Redis
spring.data.redis.host=192.168.40.21
spring.data.redis.port=6379

spring.session.redis.configure-action=NOTIFY_KEYSPACE_EVENTS
spring.session.redis.flush-mode=on_save
spring.session.redis.namespace=spring:session
spring.session.timeout=1800

# mostrar logs detalhados
logging.level.org.springframework.session=DEBUG
logging.level.org.springframework.data.redis=DEBUG
