# Postgres Connection
spring.datasource.url=jdbc:postgresql://192.168.40.21:5432/dns_database
spring.datasource.username=bind_user
spring.datasource.password=password_dlz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Dialeto para o PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
