spring.application.name=rr-dns
server.port=8080

# --- CONEXÃO COM O BANCO ---
spring.datasource.url=jdbc:postgresql://192.168.40.21:5432/dns_database
spring.datasource.username=bind_user
spring.datasource.password=password_dlz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- CONEXÃO COM O REDIS ---
spring.data.redis.host=192.168.40.21
spring.data.redis.port=6379
spring.session.store-type=redis
spring.session.redis.flush-mode=on_save
spring.session.redis.namespace=spring:session

spring.jpa.open-in-view=false
jwt.secret=hT7eY63-kJe992A908asd980Aasn)@*
jwt.expiration=86400000

# Formatar SQL deixando mais legível
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.SQL=DEBUG

# Logar requisições, erros e validação
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.validation=DEBUG
logging.level.org.springframework.security=DEBUG
# logging.level.com.seu.pacote=DEBUG 
