spring.application.name=rr-dns
spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

# Hibernate
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=hT7eY63-kJe992A908asd980Aasn)@*