spring.application.name=rr-dns
#spring.profiles.active=test

server.port=8080

# --- CONEXÃO COM O BANCO ---
spring.datasource.url=jdbc:postgresql://192.168.40.21:5432/dns_database
spring.datasource.username=bind_user
spring.datasource.password=password_dlz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=hT7eY63-kJe992A908asd980Aasn)@*

# Formatar SQL deixando mais legível
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.SQL=DEBUG

# Logar requisições, erros e validação
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.validation=DEBUG
logging.level.org.springframework.security=DEBUG
# logging.level.com.seu.pacote=DEBUG 
